apiVersion: batch/v1
kind: Job
metadata:
  # Custom Ignite cluster's name.
  name: transe
spec:
  template:
    metadata:
      labels:
        app: ignite
    spec:
      serviceAccountName: ignite
      containers:
        # Custom Ignite pod name.
      - name: ignite
        image: gcr.io/crypto-topic-270614/master:te2
        volumeMounts:
        - name: transe-data
          mountPath: /opt/ignite/apache-ignite
        env:
        - name: OPTION_LIBS
          value: ignite-kubernetes
        - name: CONFIG_URI
          value: https://raw.githubusercontent.com/xhulja07/igniteconfig/master/kube-persistence.xml
        ports:
        # Ports to open.
        # Might be optional depending on your Kubernetes environment.
        - containerPort: 11211 # REST port number.
        - containerPort: 47100 # communication SPI port number.
        - containerPort: 47500 # discovery SPI port number.
        - containerPort: 49112 # JMX port number.
        - containerPort: 10800 # SQL port number.
        - containerPort: 10900 # Thin clients port number.
      restartPolicy: Never
      volumes:
        - name: transe-data
          emptyDir: {}
